### PR TITLE
Swift 2.2

### PR DESCRIPTION
**Pull request by ikesyo**
Make the tests buildable with Xcode 7.3.

### CODE REVIEW

**Comment by jdhealy** [comment]
Hey, thanks for the PR :sparkles: 

The type annotations needed for [that array in the tests](https://github.com/jdhealy/PrettyColors/pull/9/commits/94008f08ff4df29d7fac35f7cd589fe0075b0f64#diff-ee28f00e5658d3af153ff81c8399cedcL393) changed again at some point with Swift `3.0-dev`. Type annotating the entire array of tuples as `[(Color.Wrap, String)]`, seems to work with both Swift `2.2` and `3.0-dev`, [so I pushed that to the development branch](https://github.com/jdhealy/PrettyColors/commit/8781dab5f905a48d026b6d538f0b4814000153bd).

I will have more time tonight to look into the `xcscheme` changes, and then tag and ship a release.

Thanks again! :smile:

**Comment by jdhealy** [comment]
### `xcscheme` changes

I also, at some point, had Xcode move the `buildConfiguration` declarations to the top of their elements. 

Despite testing with the Carthage `xcworkspace`, CocoaPods, playground workspaces, and PrettyColors.xcodeproj in `xcodebuild` and Xcode 7.3.0, I couldn't reproduce even the suggestion of moving the `buildConfiguration` declarations.

So, I left them unmoved — if Xcode decides in the future to move them again, I will cherry pick your commit.

**[Build Action Entries](https://github.com/jdhealy/PrettyColors/pull/9/commits/88b907f56af27e78e8ad59e09baf92ac3d3ba155#diff-e1277a683e93ee5b15f314298fe59fa3L23)**: Not clear to me why these `BuildActionEntry` changes were made, let me know if they're important and I can rollout another point release.

### [`v3.0.1` Release](https://github.com/jdhealy/PrettyColors/releases/tag/v3.0.1) :tada:

Thanks again for the PR, going to close this out.

**Comment by ikesyo** [comment]
Thanks for cutting the new release! :tada: 

> Despite testing with the Carthage xcworkspace, CocoaPods, playground workspaces, and PrettyColors.xcodeproj in xcodebuild and Xcode 7.3.0, I couldn't reproduce even the suggestion of moving the buildConfiguration declarations.

Building the projects is not related to the change. If you open Scheme Edit view (Product > Scheme > Edit Scheme...), Xcode would automatically modifies a scheme.

> Build Action Entries: Not clear to me why these BuildActionEntry changes were made, let me know if they're important and I can rollout another point release.

If `buildForRunning` is set to YES, the test target is always built if you build the framework target (⌘ R in Xcode or `xcodebuild build`, not `xcodebuild test`). That is not desirable because building the test target is not necessary in those cases and would consume extra times for `carthage update` / `carthage build`. And also in today's Xcode project template, only `buildForTesting` is set to YES by default for test targets.

**Comment by ikesyo** [comment]
https://github.com/Carthage/Carthage/issues/515 and https://github.com/Carthage/Carthage/issues/517 would help you too. :wink:

**Comment by jdhealy** [comment]
@ikesyo Thanks for the explanation and the links!

I've [cherry-picked the commit into `development` and amended the commit message to include those](https://github.com/jdhealy/PrettyColors/commit/8dbfa702c6d405f7f612b5b197184e524c964a5b) and if that's to your liking, then I'll ship `v3.0.2`. :ship:

**Comment by ikesyo** [comment]
@jdhealy That seems good to me. :+1: Thank you!

**Comment by jdhealy** [comment]
Cut [`v3.0.2`](https://github.com/jdhealy/PrettyColors/releases/tag/v3.0.2) release! :scissors: :+1:

Thanks, @ikesyo :sparkles:

**Pull request closed without merging**
