### PR TITLE
Merge Swift 3 support into master

### PR DESCRIPTION
**Pull request by ikesyo**
It would be great if we get a new release which supports Swift 3. 😃 

Ref: #14

### CODE REVIEW

**Comment by ikesyo** [comment]
@jdhealy I'm sorry to bother you, but is there any news on a new Swift 3 compatible release? Looks like some works are done on your `development` branch.

**Comment by jdhealy** [comment]
@ikesyo No, my apologies. I have some time scheduled away tomorrow to test on a local Linux machine, then tag and ship a release.

Appreciate the huge amount of [`swift3-prep`](https://github.com/Carthage/Carthage/search?q=swift3-prep&type=Issues) that you've been doing on Carthage!

**Comment by mdiep** [comment]
*bump*

**Comment by jdhealy** [comment]
### 5.0.0: Swift 3 · Support Swift Package Manager
https://github.com/jdhealy/PrettyColors/releases/tag/5.0.0

**Pull request closed without merging**
