### PR TITLE
Swift 2.3 · Reduce to single framework target and single scheme · Support tvOS and watchOS

### PR DESCRIPTION
**Pull request by jdhealy**
Reduce to single framework target, configured with `jdhealy/FABConfig`.
- Reduce to single test target, also configured with `jdhealy/FABConfig`.
- Reduce to single scheme.
- Support additional platforms of tvOS and watchOS and corresponding simulators.
- Set `CODE_SIGNING_REQUIRED` to `NO` (through `jdhealy/FABConfig`).
  - Remove configuration `CODE_SIGN_IDENTITY[sdk=iphoneos*] = "iPhone Developer"`.
  - Trust in Xcode 8+ automatic code signing defaults.
    - Code signing will usually still be required at the point of embedding PrettyColors in a code-signed bundle.
    - See https://github.com/jdhealy/FABConfig/pull/1 for more info.
- Set SWIFT_VERSION to 2.3, solely to prevent Xcode from offering the Swift Migrator.
  - No source migration was necessary; compatibility with Swift 2.2 remains.

### CODE REVIEW

**Comment by jdhealy** [comment]
This passed decently-thorough testing on my machine. But as a complicated changeset involving pbxproj, submodule, and xcconfig changes, I'd like to extensively test building it on external build machines with multiple tools.

**Comment by ikesyo** [comment]
Thanks for the work and this works for me.

Just a note, selecting `Generic tvOS Device` and building for testing (Shift-Cmd-U) fails. But explicitly set `Don't Code Sign` for the `Code Signing Identity` build setting fixes the issue.

``` diff
diff --git a/PrettyColors.xcodeproj/project.pbxproj b/PrettyColors.xcodeproj/project.pbxproj
index dbf0dd9..210163c 100644
--- a/PrettyColors.xcodeproj/project.pbxproj
+++ b/PrettyColors.xcodeproj/project.pbxproj
@@ -391,6 +391,7 @@
            isa = XCBuildConfiguration;
            baseConfigurationReference = 6706DD681D2456FF00B22F19 /* Configuration.xcconfig */;
            buildSettings = {
+               CODE_SIGN_IDENTITY = "";
                INFOPLIST_FILE = "Tests/Supporting Files/Info.plist";
                PRODUCT_BUNDLE_IDENTIFIER = "com.jdhealy.$(PRODUCT_NAME:rfc1034identifier)";
                SWIFT_VERSION = 2.3;
@@ -401,6 +402,7 @@
            isa = XCBuildConfiguration;
            baseConfigurationReference = 6706DD681D2456FF00B22F19 /* Configuration.xcconfig */;
            buildSettings = {
+               CODE_SIGN_IDENTITY = "";
                INFOPLIST_FILE = "Tests/Supporting Files/Info.plist";
                PRODUCT_BUNDLE_IDENTIFIER = "com.jdhealy.$(PRODUCT_NAME:rfc1034identifier)";
                SWIFT_VERSION = 2.3;
```

**Comment by jdhealy** [comment]
- [x] Update `podspec` with added platforms.
  - [x] Link to this comment in that commit message.
  - [x] Link to Swift 3 commit which added the platforms below.

### Commits which enabled additional platforms
- Swift 2.3 — jdhealy/PrettyColors@42b04b78f01f47faf197288da6571bfb387eb70c
- Swift 3.0 — jdhealy/PrettyColors@168391c38015c556d2b839719316bc3d9d1366b5

**Comment by mdiep** [comment]
Is there remaining work to be done on this?

Xcode 8 GM and macOS Sierra are right around the corner, and I'd like Carthage to be Xcode 7/8 compatible on Day 1. 😄

**Pull request merged**
